cabal: true
steps:
  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always
  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
language_extensions:
  - StrictData
  - CPP
columns: 120
newline: lf
